### ISSUE TITLE
Android crash with urbanairship-chat-react-native

### ISSUE THREAD

**Issue by elsadronet1** [urbanairship/react-native-module#365]
# Preliminary Info

### What Airship dependencies are you using?
		"urbanairship-chat-react-native": "^13.0.0",
		"urbanairship-react-native": "^13.0.0"

### What are the versions of any relevant development tools you are using?
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 736.74 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/edronet/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

# Report

### What unexpected behavior are you seeing?
App crashing at start with urbanairship-chat-react-native module
Ok only with urbanairship-react-native

### Do you have logging for the issue?
E/AndroidRuntime: FATAL EXCEPTION: UrbanAirship#2
    Process: com.dosatron.mobile, PID: 22876
    java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
        at kotlinx.coroutines.internal.MainDispatchersKt.throwMissingMainDispatcherException(MainDispatchers.kt:76)
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:107)
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:91)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:302)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:171)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at com.urbanairship.chat.Conversation$updateConnection$2.invokeSuspend(Conversation.kt:285)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at com.urbanairship.util.SerialExecutor$1.run(SerialExecutor.java:41)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
        at java.lang.Thread.run(Thread.java:929)

**Comment by rlepinski** [comment]
Could you try again with 13.0.2 ?

**Comment by elsadronet1** [comment]
Same problem with 13.0.2

**Comment by elsadronet1** [comment]
With version 13.0.2 of urbanairship-chat-react-native and urbanairship-react-native, it's running. 
Thank you !
