### ISSUE TITLE
Question about running a app on Android emulator without a valid development app key

### ISSUE THREAD

**Issue by cchristman-shell** [urbanairship/react-native-module#406]
Hello,

I have a question about the key for urbanairship. We don't have a valid "development app key" for User Notifications in a test application.  We are trying to test the app in an Android simulator (Pixel 2 API 30), Android Studio logs this error at run time: "java.lang.IllegalArgumentException: AirshipConfigOptions: appKey is not a valid development app key", and the app keeps stopping.  

E/AndroidRuntime: FATAL EXCEPTION: UrbanAirship#1
    Process: com.shell, PID: 7383
    java.lang.IllegalArgumentException: AirshipConfigOptions: appKey is not a valid development app key
        at com.urbanairship.AirshipConfigOptions.validate(AirshipConfigOptions.java:383)
        at com.urbanairship.UAirship.executeTakeOff(UAirship.java:402)
        at com.urbanairship.UAirship.access$000(UAirship.java:65)
        at com.urbanairship.UAirship$2.run(UAirship.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
        at java.lang.Thread.run(Thread.java:923)

Do we need a valid development app key?   Is there a way to bypass the key or use an empty key that won't crash the app?

Dependencies
"urbanairship-react-native": "^9.0.0"
"react-native": "0.64.1"

Thanks,

❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What are the versions of any relevant development tools you are using?

# Report

### What is the expected behavior?

Expected the app to run in the Android simulator, but it keeps stopping.

**Comment by rlepinski** [comment]
You have a few options:
- use `appKey` and `appSecret` instead of `productionAppKey` and `productionAppSecret` on Android in the config
- set the `inProduction` flag to true
- generate another project for debug builds

The SDK doesnt really care about what type of app its connecting to, production vs development is just a convenience. At runtime, if its a debug build we will pull the `development` creds, otherwise the `production` creds.

**Comment by cchristman-shell** [comment]
Currently we are using "appKey" and "appSecret" in the airshipconfig.properties file, does it look correct to you?  I don't see any file that set inProduction flag, should it be set in this file?  SDK errored out with this settings.

developmentAppKey = appKey
developmentAppSecret = appSecret
productionAppKey = appKey
productionAppSecret = appSecret

We have tried to change "appKey" and "appSecret" to empty strings or left them blank, but it didn't help. The app crashed with the same error: java.lang.IllegalArgumentException: AirshipConfigOptions: '' is not a valid development app key.

**Comment by rlepinski** [comment]
Do you have any valid credentials? Can we use those for your debug build?

**Comment by cchristman-shell** [comment]
Unfortunately, we don't have any valid credentials.  It is an application that build a React app with a template.  The template includes the Urbanairship package.  We are running the test against the created React app in the GitHub pipeline.

**Comment by rlepinski** [comment]
Ok, would be nice if we could disable the plugin properly but for now you can add fake credentials that match the validation format `^[a-zA-Z0-9\\-_]{22}$``0000000000000000000000` is technically valid. Could you also add `enabledFeatures=none` to the config? That will prevent the SDK doing anything with the fake credentials.

**Comment by cchristman-shell** [comment]
Wow, the fake key works as a charm.  Thanks for your help!

**Comment by rlepinski** [comment]
🎉

**Comment by rlepinski** [comment]
@cchristman-shell I released 14.1.0 that makes setting config/takeoff optional. You should be able to remove the fake config file
