### ISSUE TITLE
java.lang.NullPointerException when accessing preferences

### ISSUE THREAD

**Issue by georgexu22** [urbanairship/react-native-module#433]
# Preliminary Info
We're seeing intermittent App Crashes on Android. We think it's related to the changes introduced in 14.1 based on the changelog.

### What Airship dependencies are you using?
14.3

# Report

### What unexpected behavior are you seeing?
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference
        at com.urbanairship.reactnative.ReactAirshipPreferences.getBoolean(ReactAirshipPreferences.java:212)
        at com.urbanairship.reactnative.ReactAirshipPreferences.getOptInStatus(ReactAirshipPreferences.java:172)
        at com.urbanairship.reactnative.UrbanAirshipReactModule.checkOptIn(UrbanAirshipReactModule.java:1312)
        at com.urbanairship.reactnative.UrbanAirshipReactModule.lambda$initialize$0(UrbanAirshipReactModule.java:130)
        at com.urbanairship.reactnative.UrbanAirshipReactModule.lambda$initialize$0$UrbanAirshipReactModule(Unknown)
        at com.urbanairship.reactnative.-$$Lambda$UrbanAirshipReactModule$N05ngLli5RmMNY-8aTuIHysXrLU.onAirshipReady(Unknown:2)
        at com.urbanairship.UAirship$1.onRun(UAirship.java:270)
        at com.urbanairship.CancelableOperation$1.run(CancelableOperation.java:58)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:920)
```

### What is the expected behavior?
App should not crash

### What are the steps to reproduce the unexpected behavior?
N/A

**Comment by Ulrico972** [comment]
Hello, we'll take care of it as soon as possible.

**Comment by Ulrico972** [comment]
Hello, we pushed a patch release (14.3.1) for this issue.
Feel free to reopen if that doesn't solve the problem.
