### ISSUE TITLE
NullPointerException when invoke loadMessage function

### ISSUE THREAD

**Issue by Peter-ChengTszTung** [urbanairship/react-native-module#439]
# Preliminary Info

### What Airship dependencies are you using?

`"urbanairship-react-native": "14.2.1"`

# Report

### What unexpected behavior are you seeing?

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.urbanairship.messagecenter.webkit.MessageWebView.loadMessage(com.urbanairship.messagecenter.Message)' on a null object reference
    at com.urbanairship.reactnative.ReactMessageView$2.onFinished(ReactMessageView.java:121)
    at com.urbanairship.messagecenter.Inbox$PendingFetchMessagesCallback.onRun(Inbox.java:809)
    at com.urbanairship.CancelableOperation$1.run(CancelableOperation.java:58)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### What is the expected behavior?

- Should not receive crash report

### What are the steps to reproduce the unexpected behavior?
- N/A

**Comment by khmMouna** [comment]
I am not able de reproduce. Can I see how you implement the message center, please?
